# -*- ruby -*-

require 'rubygems'
require 'hoe'
require './lib/erector_generators.rb'

Hoe.new('erector_generators', ErectorGenerators::VERSION) do |p|
  p.developer('mkristian', 'm.kristian@web.de')
  p.extra_deps = ['rspec-rails', 'erector']
end

desc 'Install the package as a gem.'
task :install => [:clean, :package] do
  gem = Dir['pkg/*.gem'].first
  sh "gem install --local #{gem} --no-ri --no-rdoc"
end

# vim: syntax=Ruby
